---
title: "utilisation de photos"
author: "B. Maranget"
date: "20/12/2023"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

Recensement mobilier publicitaire de la commune, inventaire photo.
Faire une appli leaflet avec les photos

Attention version 1 sur ordi boulot

sources :
- tableau Habib
- photos Habib

pour le test

- photo fontaine
- pt photo (un point sur bondy)

https://marionlouveaux.fr/fr/blog/gpx-tracks-and-leaflet-interactive-map/


# Données


```{r}
library(sf)
library(mapsf)
library(dplyr)
library(leaflet)
chemin <-  paste0(Sys.getenv('HOME'), "/03_SIG/03_03_Data/08_VOIRIE/")
```


```{r}
st_layers("../data/cadastre.gpkg")
data <- st_read("../data/cadastre.gpkg")
enseigne <- st_read("../data/cadastre.gpkg", "enseigne")
mf_map(enseigne)
enseigne <- st_centroid(enseigne)
mf_map(enseigne, ad = T)
#mf_label(enseigne, "Enseigne")
names(enseigne)
enseigne <- enseigne [9,]
mf_map(enseigne, add = T, col="red")
enseigne <-c <-st_coordinates(enseigne)
cbind(enseigne, c)
```


joindre enseigne et photo

```{r}
m <- leaflet()
m <- addTiles(m)
m <- addMarkers(m, enseigne$geom, popup="Test fontaine")
m

leaflet(data = enseigne %>% addTiles() %>%
  addMarkers(~X, ~Y, popup = ~enseigne, label = ~enseigne)

```


