---
title: "Mobilier publicitaire - affichage photos"
author: "H. Bellaouedj, B. Maranget"
date: "26/12/2023"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```









```{r , eval=TRUE}
library(dplyr)
library(leaflet)
library(leafpop)
#(lubridate)
#library(purrr)
#library(readr)
library(sf)
#library(mapsf)
library(tibble)
library(tidyr)
```


```{r}
data <- read.csv2("../data/mobPublicitaire.csv")
knitr::kable(data, caption = paste0(length(data$dispositif), " panneaux 2m²"))
```


```{r, eval=TRUE}
cameraIcon <- iconList(makeIcon("../img/240px-Icone_appareil_photo.png", iconWidth = 30))
data <- st_read("../data/mobPublicitaire.gpkg", "2m", quiet = T)
data <- st_transform(data, crs = 4326)
leaflet(width = 800, height = 900) %>%
  addProviderTiles("OpenStreetMap.France") %>%
  addMarkers(data = data, label = ~TERRAIN, group = "photos", icon = ~cameraIcon) %>%
  addPopupImages(data$chemin, group = "photos", width = 150, height = 200) 
```

